### ISSUE TITLE
Firefox error due to TLS 1.0

### ISSUE THREAD

**Issue by DerKnerd** [ice/website#43]
Hi @all,

I just wanted to checkout your website and got an error message in Firefox, cause the website uses TLS 1.0 can you upgrade it to TLS 1.2?

Greetings
Knerd

**Comment by mruz** [comment]
I have to migrate the website to another server, because it's difficult to upgrade the current one. I'll do it soon. Thanks for the report!

**Comment by mruz** [comment]
I upgraded.
